# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         URI-ImpliedBase
version:      0.04
version_from: lib/URI/ImpliedBase.pm
installdirs:  site
requires:
    Cwd:                           0
    Test::Simple:                  0.44
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
